name: pylops_t21
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - numpy>=1.15.0
  - scipy>=1.4.0
  - matplotlib
  - pylops==1.13.0
  - ipython
  - jupyter
  - pip:
    - pympler
    - pyproximal==0.0.0
    - scooby
    - segyio